#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 12

#缓存
cache:
  directories:
    - node_modules

#发布
# deploy:
#   - provider: npm
#     email: kezhongfa@163.com
#     skip_cleanup: true
#     api_key: $NPM_API_KEY
#     on:
#       tags: true
#     tag: latest

notifications:
  email:
    recipients:
      - 1170212530@qq.com
    on_success: never # default: change
    on_failure: always # default: always
